version: '3'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
